%% Fluorescence signal analysis pipeline
%
% This pipeline converts fluorescence image stacks into ROI fluorescence
% signals and then detects fluorescence events from those signals.
%
% The analysis consists of two steps:
%
%   Step 1: Run image2signal
%           Extract fluorescence signals from ImageJ/Fiji ROIs.
%
%   Step 2: Run plotSpike
%           Process the fluorescence signals, detect events, inspect the
%           results, and manually correct detected events if necessary.
%
%
% ========================================================================
% BEFORE STARTING
% ========================================================================
%
% 1. In Fiji/ImageJ:
%       - Draw the ROIs to be analyzed.
%       - Save the ROIs as an ROI Set (.zip).
%
% 2. Prepare the motion-corrected TIFF image stacks.
%
%    Image files should be named:
%
%       MMM_DDD_NNN_MotCor.tif
%
%    where NNN is the ID of the recording.
%
% 3. Make sure the following scripts/functions are in the MATLAB path:
%
%       image2signal.m
%       plotSpike.m
%       ReadImageJROI.m
%       load_tiffs_fast.m
%
%    Additional functions required by plotSpike should also be available.
%
%
% ========================================================================
% STEP 1 — CONVERT IMAGES TO FLUORESCENCE SIGNALS
% ========================================================================
%
% Run:
%
%       image2signal
%
% The script will ask you to:
%
%   1. Select the ImageJ/Fiji ROI Set (.zip).
%   2. Select one or more *_MotCor.tif image files.
%
% For each image file, image2signal extracts the mean fluorescence
% intensity within each ROI across all imaging frames.
%
% The output is a MATLAB file containing:
%
%       activs
%
% where:
%
%       rows    = imaging frames
%       columns = ROIs
%
% The output file is saved in the same folder as the corresponding TIFF
% image.
%
%
% ========================================================================
% STEP 2 — DEFINE PARAMETERS FOR SPIKE ANALYSIS
% ========================================================================
%
% Before running plotSpike, define:
%
%   ROIgroup
%       Defines which ROIs are analyzed as individual signal traces.
%
%   ROIlabel
%       Defines the label displayed for each signal trace.
%
%   time
%       Timestamp of each imaging frame, in seconds.
%
%
% --- Example 1: Analyze every ROI separately ---
%
% ROIgroup = num2cell(1:58);
%
% ROIlabel = cellfun(@(x) ['Cell ' num2str(x)], ...
%     num2cell(1:length(ROIgroup)), ...
%     'UniformOutput', false);
%
%
% --- Example 2: Combine multiple ROIs into individual traces ---
%
% ROIgroup = {1:5, 6:10};
%
% ROIlabel = {'Cell 1', 'Cell 2'};
%
%
% --- Define imaging time ---
%
% Example: 310 frames acquired over 10 seconds
%
% time = 0:10/310:10-10/310;
%
%
% ========================================================================
% STEP 3 — RUN SPIKE ANALYSIS
% ========================================================================
%
% Run:
%
%       plotSpike(ROIgroup, ROIlabel, time)
%
% When the interface opens, select:
%
%       "Create New Project"
%
% and then:
%
%   1. Select the ROI analysis file(s) generated by image2signal.
%   2. Select the same ImageJ/Fiji ROI Set (.zip).
%
% plotSpike will then:
%
%   - combine ROIs according to ROIgroup;
%   - perform ROI size-weighted averaging when ROIs are grouped;
%   - perform background correction;
%   - smooth the fluorescence signals;
%   - detect fluorescence peaks;
%   - detect the rise associated with each peak;
%   - display the results in the graphical interface.
%
% Detection parameters can be adjusted in the interface.
% Detected events can also be manually added or removed.
%
% When finished, click "Save" to save the analysis as a
% *SpikeAna.mat file.
%
%
% ========================================================================
% RUN ANALYSIS
% ========================================================================


%% Step 1: Extract fluorescence signals

% Run this section first.
% Follow the dialog boxes to select the ROI set and TIFF image files.

ROI2signal


%% Step 2: Detect and analyze fluorescence events

% Run this section after image2signal has finished.
% Follow the dialog boxes to select the generated ROI analysis files.


% Define ROI groups
ROIgroup = num2cell(1:58);

% Define ROI labels
ROIlabel = cellfun(@(x) ['Cell ' num2str(x)], ...
    num2cell(1:length(ROIgroup)), ...
    'UniformOutput', false);

% Define imaging time
% Example: 310 frames acquired over 10 seconds
time = 0:10/310:10-10/310;

plotSpike(ROIgroup, ROIlabel, time);